// @ts-nocheck
// D1 (SQLite) Drizzle schema for Cloudflare Workers
// Phase 1 of Neon → D1 migration
// Generated from prisma/schema.prisma (970 lines, 34 models)
//
// Conventions:
// - cuid() for IDs (text, generated by @paralleldrive/cuid2)
// - DateTime → integer timestamp mode
// - Boolean → integer boolean mode (0/1)
// - String[] → text with mode: 'json' (8 fields)
// - Json? → text with mode: 'json' (3 fields)
// - Foreign keys with cascade per Prisma

import { sqliteTable, text, integer, real, index, uniqueIndex, primaryKey } from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';

// ============================================================================
// ID generation (CUID-like)
// ============================================================================
const generateId = () => {
  return crypto.randomUUID().replace(/-/g, '').slice(0, 25);
};

// ============================================================================
// USER & AUTH (4 models)
// ============================================================================
export const users = sqliteTable('User', {
  id:              text('id').primaryKey().$defaultFn(generateId),
  email:           text('email').notNull().unique(),
  emailVerifiedAt: integer('emailVerifiedAt', { mode: 'timestamp' }),
  passwordHash:    text('passwordHash'),
  role:            text('role').notNull().default('STUDENT'), // STUDENT | TEACHER | ADMIN
  status:          text('status').notNull().default('PENDING_OTP'),

  // OAuth
  oauthProvider:   text('oauthProvider'),
  oauthId:         text('oauthId'),

  // Profile
  firstName:       text('firstName'),
  lastName:        text('lastName'),
  firstNameAr:     text('firstNameAr'),
  lastNameAr:      text('lastNameAr'),
  avatarUrl:       text('avatarUrl'),
  bio:             text('bio'),
  phone:           text('phone'),
  website:         text('website'),
  schoolLevel:     text('schoolLevel'),
  classLevel:      text('classLevel'),
  schoolName:      text('schoolName'),
  schoolNameAr:    text('schoolNameAr'),
  governorate:     text('governorate'),

  // Teacher specific
  teachingSubjects: text('teachingSubjects', { mode: 'json' }).$type<string[]>(),
  teachingLevels:   text('teachingLevels', { mode: 'json' }).$type<string[]>(),
  cvUrl:            text('cvUrl'),
  diploma:          text('diploma'),
  isVerifiedTeacher: integer('isVerifiedTeacher', { mode: 'boolean' }).notNull().default(false),
  approvedAt:       integer('approvedAt', { mode: 'timestamp' }),
  approvedById:     text('approvedById'),

  // URL identity
  numericId:       integer('numericId').unique(),
  slug:            text('slug'),
  slugEn:          text('slugEn'),

  // Stats (denormalized)
  uploadsCount:    integer('uploadsCount').notNull().default(0),
  followersCount:  integer('followersCount').notNull().default(0),

  // Login security (2026-08-30: added when migrating login to D1)
  failedLoginCount:    integer('failedLoginCount').notNull().default(0),
  lockedUntil:         integer('lockedUntil', { mode: 'timestamp' }),
  lastFailedLoginAt:   integer('lastFailedLoginAt', { mode: 'timestamp' }),
  lastLoginAt:         integer('lastLoginAt', { mode: 'timestamp' }),

  createdAt:       integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt:       integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  emailIdx:    uniqueIndex('user_email_idx').on(table.email),
  numericIdIdx: uniqueIndex('user_numeric_id_idx').on(table.numericId),
  slugIdx:     index('user_slug_idx').on(table.slug),
  roleIdx:     index('user_role_idx').on(table.role),
}));

export const otpCodes = sqliteTable('OtpCode', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  userId:    text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  code:      text('code').notNull(),
  purpose:   text('purpose').notNull(), // LOGIN | RESET | VERIFY
  expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),
  usedAt:    integer('usedAt', { mode: 'timestamp' }),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const sessions = sqliteTable('Session', {
  id:           text('id').primaryKey().$defaultFn(generateId),
  userId:       text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  token:        text('token').notNull().unique(),
  userAgent:    text('userAgent'),
  ipAddress:    text('ipAddress'),
  expiresAt:    integer('expiresAt', { mode: 'timestamp' }).notNull(),
  createdAt:    integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  userIdIdx: index('session_user_id_idx').on(table.userId),
  tokenIdx:  uniqueIndex('session_token_idx').on(table.token),
}));

// ============================================================================
// CATALOG (4 models: Level, Class, Section, Subject)
// ============================================================================
export const levels = sqliteTable('Level', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  numericId: integer('numericId').unique(),
  slug:      text('slug').notNull().unique(),
  nameFr:    text('nameFr').notNull(),
  nameAr:    text('nameAr').notNull(),
  order:     integer('order').notNull().default(0),
  schoolType: text('schoolType').notNull().default('PUBLIC'), // PUBLIC | PILOTE | PRIVÉ
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const classes = sqliteTable('Class', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  numericId: integer('numericId').unique(),
  slug:      text('slug').notNull(),
  nameFr:    text('nameFr').notNull(),
  nameAr:    text('nameAr').notNull(),
  order:     integer('order').notNull().default(0),
  levelId:   text('levelId').notNull().references(() => levels.id, { onDelete: 'Cascade' }),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  levelIdx:    index('class_level_idx').on(table.levelId),
  slugIdx:     index('class_slug_idx').on(table.slug),
  numericIdIdx: uniqueIndex('class_numeric_id_idx').on(table.numericId),
}));

export const sections = sqliteTable('Section', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  numericId: integer('numericId').unique(),
  slug:      text('slug').notNull(),
  nameFr:    text('nameFr').notNull(),
  nameAr:    text('nameAr').notNull(),
  order:     integer('order').notNull().default(0),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  slugIdx:     index('section_slug_idx').on(table.slug),
  numericIdIdx: uniqueIndex('section_numeric_id_idx').on(table.numericId),
}));

export const subjects = sqliteTable('Subject', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  numericId: integer('numericId').unique(),
  slug:      text('slug').notNull().unique(),
  nameFr:    text('nameFr').notNull(),
  nameAr:    text('nameAr').notNull(),
  icon:      text('icon'),
  color:     text('color'),
  order:     integer('order').notNull().default(0),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  slugIdx: index('subject_slug_idx').on(table.slug),
}));

// ============================================================================
// RESOURCE & CONTENT (5 models: Resource, ResourceContent, ResourceMetadata, ResourceSummary, TeacherVerificationFile, TeacherFile)
// ============================================================================
export const resources = sqliteTable('Resource', {
  id:           text('id').primaryKey().$defaultFn(generateId),
  numericId:    integer('numericId').unique(),
  slug:         text('slug').notNull(),
  title:        text('title').notNull(),
  description:  text('description'),
  summary:      text('summary'),
  type:         text('type').notNull(), // EXERCISE | LESSON | EXAM | HOMEWORK | SUMMARY | OTHER
  status:       text('status').notNull().default('DRAFT'), // DRAFT | PUBLISHED | ARCHIVED

  // File storage
  fileKey:      text('fileKey').notNull(),
  fileUrl:      text('fileUrl').notNull().unique(),
  fileSize:     integer('fileSize').notNull().default(0),
  pageCount:    integer('pageCount'),
  thumbnailKey: text('thumbnailKey'),
  thumbnailUrl: text('thumbnailUrl'),
  r2Key:        text('r2Key'),

  // Categorization
  classId:      text('classId').references(() => classes.id, { onDelete: 'SetNull' }),
  sectionId:    text('sectionId').references(() => sections.id, { onDelete: 'SetNull' }),
  subjectId:    text('subjectId').notNull().references(() => subjects.id, { onDelete: 'Restrict' }),
  teacherId:    text('teacherId').references(() => users.id, { onDelete: 'SetNull' }),

  trimester:    text('trimester'),
  year:         text('year'),
  tags:         text('tags'), // comma-separated
  language:     text('language').notNull().default('fr'),

  // AI-generated SEO fields
  metaDescription:        text('metaDescription'),
  descriptionGeneratedAt: integer('descriptionGeneratedAt', { mode: 'timestamp' }),
  descriptionSource:     text('descriptionSource'),

  // Header data extracted from PDF text
  headerData:    text('headerData', { mode: 'json' }).$type<Record<string, any>>(),
  schoolName:    text('schoolName'),
  teacherNameAr: text('teacherNameAr'),

  // Homework subtype (when type=HOMEWORK)
  homeworkSubtype: text('homeworkSubtype'),
  homeworkNumber:  integer('homeworkNumber'),

  // School type
  schoolType: text('schoolType'),

  // Quality flags
  hasCorrection:   integer('hasCorrection', { mode: 'boolean' }).notNull().default(false),
  isHidden:        integer('isHidden', { mode: 'boolean' }).notNull().default(false),
  isFeatured:      integer('isFeatured', { mode: 'boolean' }).notNull().default(false),

  // Stats (denormalized counters)
  viewsCount:     integer('viewsCount').notNull().default(0),
  downloadsCount: integer('downloadsCount').notNull().default(0),
  avgRating:      real('avgRating').notNull().default(0),
  ratingsCount:   integer('ratingsCount').notNull().default(0),
  commentsCount:  integer('commentsCount').notNull().default(0),
  favoritesCount: integer('favoritesCount').notNull().default(0),

  // Publication
  publishedAt:  integer('publishedAt', { mode: 'timestamp' }),
  createdAt:    integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt:    integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  slugIdx:          index('resource_slug_idx').on(table.slug),
  statusIdx:        index('resource_status_idx').on(table.status),
  numericIdIdx:     uniqueIndex('resource_numeric_id_idx').on(table.numericId),
  subjectClassIdx:  index('resource_subject_class_idx').on(table.subjectId, table.classId),
  teacherIdx:       index('resource_teacher_idx').on(table.teacherId),
  publishedAtIdx:   index('resource_published_at_idx').on(table.publishedAt),
  typeIdx:          index('resource_type_idx').on(table.type),
  schoolTypeIdx:    index('resource_school_type_idx').on(table.schoolType),
  hasCorrectionIdx: index('resource_has_correction_idx').on(table.hasCorrection),
  viewsIdx:         index('resource_views_idx').on(table.viewsCount),
  downloadsIdx:     index('resource_downloads_idx').on(table.downloadsCount),
}));

export const resourceContents = sqliteTable('ResourceContent', {
  resourceId: text('resourceId').primaryKey().references(() => resources.id, { onDelete: 'Cascade' }),
  text:       text('text'),
  pages:      integer('pages'),
  wordCount:  integer('wordCount'),
  charCount:  integer('charCount'),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const resourceMetadata = sqliteTable('ResourceMetadata', {
  resourceId:    text('resourceId').primaryKey().references(() => resources.id, { onDelete: 'Cascade' }),
  // AI-extracted (BILINGUAL — French + Arabic for Tunisian schools)
  systemName:     text('systemName'),     // "BAC Mathématiques" or "باكالوريا رياضيات"
  subject:        text('subject'),         // extracted subject name
  profNames:      text('profNames', { mode: 'json' }).$type<string[]>(),  // ["Mr. X", "Mme Y"]
  dossierTechnique: text('dossierTechnique'),
  shortKeyPoints: text('shortKeyPoints', { mode: 'json' }).$type<string[]>(),
  keyPoints:      text('keyPoints', { mode: 'json' }).$type<string[]>(),
  topics:         text('topics', { mode: 'json' }).$type<string[]>(),
  level:          text('level'),
  estimatedTimeMinutes: integer('estimatedTimeMinutes'),
  prerequisites:  text('prerequisites', { mode: 'json' }).$type<string[]>(),
  keyInsights:    text('keyInsights', { mode: 'json' }).$type<string[]>(),
  exerciseInsights: text('exerciseInsights', { mode: 'json' }).$type<string[]>(),
  updatedAt:      integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const resourceSummaries = sqliteTable('ResourceSummary', {
  resourceId: text('resourceId').primaryKey().references(() => resources.id, { onDelete: 'Cascade' }),
  summary:    text('summary'), // Full AI-generated summary
  language:   text('language').notNull().default('fr'),
  model:      text('model'), // "gpt-4o-mini" etc
  generatedAt: integer('generatedAt', { mode: 'timestamp' }),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  langIdx: index('resource_summary_lang_idx').on(table.language),
}));

// ============================================================================
// INTERACTIONS (7 models)
// ============================================================================
export const comments = sqliteTable('Comment', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  content:    text('content').notNull(),
  isHidden:   integer('isHidden', { mode: 'boolean' }).notNull().default(false),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  resourceIdx: index('comment_resource_idx').on(table.resourceId),
  userIdx:     index('comment_user_idx').on(table.userId),
  createdAtIdx: index('comment_created_at_idx').on(table.createdAt),
}));

export const ratings = sqliteTable('Rating', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  value:      integer('value').notNull(), // 1-5
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  uniquePair: uniqueIndex('rating_unique_idx').on(table.resourceId, table.userId),
  resourceIdx: index('rating_resource_idx').on(table.resourceId),
}));

export const favorites = sqliteTable('Favorite', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  uniquePair: uniqueIndex('favorite_unique_idx').on(table.resourceId, table.userId),
  userIdx:    index('favorite_user_idx').on(table.userId),
}));

export const views = sqliteTable('View', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  ipAddress:  text('ipAddress'),
  userAgent:  text('userAgent'),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  resourceIdx: index('view_resource_idx').on(table.resourceId),
  createdAtIdx: index('view_created_at_idx').on(table.createdAt),
}));

export const downloads = sqliteTable('Download', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  ipAddress:  text('ipAddress'),
  userAgent:  text('userAgent'),
  original:   integer('original', { mode: 'boolean' }).notNull().default(false),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  resourceIdx: index('download_resource_idx').on(table.resourceId),
  userIdx:     index('download_user_idx').on(table.userId),
  createdAtIdx: index('download_created_at_idx').on(table.createdAt),
}));

export const shares = sqliteTable('Share', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  platform:   text('platform').notNull(), // 'facebook' | 'twitter' | 'whatsapp' | 'copy' | 'email'
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const reports = sqliteTable('Report', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  resourceId: text('resourceId').notNull().references(() => resources.id, { onDelete: 'Cascade' }),
  userId:     text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  reason:     text('reason').notNull(), // 'broken_link' | 'wrong_content' | 'spam' | 'copyright' | 'other'
  details:    text('details'),
  status:     text('status').notNull().default('PENDING'), // PENDING | REVIEWED | RESOLVED
  reviewedById: text('reviewedById'),
  reviewedAt:   integer('reviewedAt', { mode: 'timestamp' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  resourceIdx: index('report_resource_idx').on(table.resourceId),
  statusIdx:   index('report_status_idx').on(table.status),
}));

// ============================================================================
// TEACHER FILES & MISC (3 models)
// ============================================================================
export const teacherVerificationFiles = sqliteTable('TeacherVerificationFile', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  userId:     text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  type:       text('type').notNull(), // DIPLOMA | ID_CARD | EMPLOYMENT_LETTER
  fileKey:    text('fileKey').notNull(),
  fileUrl:    text('fileUrl').notNull(),
  mimeType:   text('mimeType'),
  fileSize:   integer('fileSize'),
  status:     text('status').notNull().default('PENDING'), // PENDING | APPROVED | REJECTED
  reviewedById: text('reviewedById'),
  reviewedAt:   integer('reviewedAt', { mode: 'timestamp' }),
  rejectionReason: text('rejectionReason'),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  userIdx: index('teacher_verif_user_idx').on(table.userId),
  statusIdx: index('teacher_verif_status_idx').on(table.status),
}));

export const teacherFiles = sqliteTable('TeacherFile', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  teacherId:  text('teacherId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  resourceId: text('resourceId').references(() => resources.id, { onDelete: 'SetNull' }),
  fileName:   text('fileName').notNull(),
  fileKey:    text('fileKey').notNull(),
  fileUrl:    text('fileUrl').notNull(),
  r2Key:      text('r2Key'),
  r2PdfKey:   text('r2PdfKey'),
  fileSize:   integer('fileSize'),
  mimeType:   text('mimeType'),
  isActive:   integer('isActive', { mode: 'boolean' }).notNull().default(true),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  teacherIdx: index('teacher_file_teacher_idx').on(table.teacherId),
  resourceIdx: index('teacher_file_resource_idx').on(table.resourceId),
}));

export const notifications = sqliteTable('Notification', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  userId:     text('userId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  type:       text('type').notNull(),
  title:      text('title').notNull(),
  body:       text('body'),
  link:       text('link'),
  isRead:     integer('isRead', { mode: 'boolean' }).notNull().default(false),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  userIdx: index('notif_user_idx').on(table.userId),
  isReadIdx: index('notif_is_read_idx').on(table.isRead),
}));

export const newsletters = sqliteTable('Newsletter', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  email:      text('email').notNull().unique(),
  isActive:   integer('isActive', { mode: 'boolean' }).notNull().default(true),
  source:     text('source'),
  subscribedAt: integer('subscribedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  unsubscribedAt: integer('unsubscribedAt', { mode: 'timestamp' }),
}, (table) => ({
  activeIdx: index('newsletter_active_idx').on(table.isActive),
}));

export const teacherInvitations = sqliteTable('TeacherInvitation', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  email:      text('email').notNull(),
  token:      text('token').notNull().unique(),
  invitedById: text('invitedById').references(() => users.id, { onDelete: 'SetNull' }),
  status:     text('status').notNull().default('PENDING'), // PENDING | ACCEPTED | EXPIRED | REVOKED
  message:    text('message'),
  expiresAt:  integer('expiresAt', { mode: 'timestamp' }).notNull(),
  acceptedAt: integer('acceptedAt', { mode: 'timestamp' }),
  invitationSentAt: integer('invitationSentAt', { mode: 'timestamp' }),
  invitationActivatedAt: integer('invitationActivatedAt', { mode: 'timestamp' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const settings = sqliteTable('Setting', {
  key:        text('key').primaryKey(),
  value:      text('value').notNull(),
  description: text('description'),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const follows = sqliteTable('Follow', {
  id:           text('id').primaryKey().$defaultFn(generateId),
  followerId:   text('followerId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  followingId:  text('followingId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  createdAt:    integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  uniquePair: uniqueIndex('follow_unique_idx').on(table.followerId, table.followingId),
  followerIdx: index('follow_follower_idx').on(table.followerId),
  followingIdx: index('follow_following_idx').on(table.followingId),
}));

// ============================================================================
// MESSAGING (3 models: Conversation, Message, ContactMessage)
// ============================================================================
export const conversations = sqliteTable('Conversation', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  user1Id:    text('user1Id').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  user2Id:    text('user2Id').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  lastMessageAt: integer('lastMessageAt', { mode: 'timestamp' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  user1Idx: index('conv_user1_idx').on(table.user1Id),
  user2Idx: index('conv_user2_idx').on(table.user2Id),
  lastMsgIdx: index('conv_last_msg_idx').on(table.lastMessageAt),
}));

export const messages = sqliteTable('Message', {
  id:             text('id').primaryKey().$defaultFn(generateId),
  conversationId: text('conversationId').notNull().references(() => conversations.id, { onDelete: 'Cascade' }),
  senderId:       text('senderId').notNull().references(() => users.id, { onDelete: 'Cascade' }),
  content:        text('content').notNull(),
  isRead:         integer('isRead', { mode: 'boolean' }).notNull().default(false),
  readAt:         integer('readAt', { mode: 'timestamp' }),
  createdAt:      integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  convIdx: index('msg_conv_idx').on(table.conversationId),
  createdAtIdx: index('msg_created_at_idx').on(table.createdAt),
}));

export const contactMessages = sqliteTable('ContactMessage', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  name:       text('name').notNull(),
  email:      text('email').notNull(),
  subject:    text('subject'),
  message:    text('message').notNull(),
  status:     text('status').notNull().default('PENDING'), // PENDING | READ | REPLIED
  repliedAt:  integer('repliedAt', { mode: 'timestamp' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  statusIdx: index('contact_status_idx').on(table.status),
}));

// ============================================================================
// SEARCH & ANALYTICS (2 models: SearchSynonym, SearchLog)
// ============================================================================
export const searchSynonyms = sqliteTable('SearchSynonym', {
  id:        text('id').primaryKey().$defaultFn(generateId),
  term:      text('term').notNull(),
  synonyms:  text('synonyms', { mode: 'json' }).$type<string[]>().notNull(), // ['mathematiques', 'رياضيات']
  locale:    text('locale').notNull().default('fr'),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  termIdx: index('synonym_term_idx').on(table.term),
  localeIdx: index('synonym_locale_idx').on(table.locale),
}));

export const searchLogs = sqliteTable('SearchLog', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  query:      text('query').notNull(),
  userId:     text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  ipAddress:  text('ipAddress'),
  resultsCount: integer('resultsCount').notNull().default(0),
  clickedResourceId: text('clickedResourceId').references(() => resources.id, { onDelete: 'SetNull' }),
  locale:     text('locale').notNull().default('fr'),
  source:     text('source').notNull().default('search_bar'), // search_bar | suggest | browse
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  queryIdx: index('search_log_query_idx').on(table.query),
  userIdx: index('search_log_user_idx').on(table.userId),
  createdAtIdx: index('search_log_created_at_idx').on(table.createdAt),
}));

// ============================================================================
// API PROVIDERS & LOGS (4 models: ApiProvider, ApiProviderUsage, ErrorLog, VercelLog)
// ============================================================================
export const apiProviders = sqliteTable('ApiProvider', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  name:       text('name').notNull().unique(),
  type:       text('type').notNull(), // 'openai' | 'anthropic' | 'mistral' | etc
  apiKey:     text('apiKey'),
  baseUrl:    text('baseUrl'),
  model:      text('model'),
  isActive:   integer('isActive', { mode: 'boolean' }).notNull().default(true),
  priority:   integer('priority').notNull().default(0),
  config:     text('config', { mode: 'json' }).$type<Record<string, any>>(),
  lastUsedAt: integer('lastUsedAt', { mode: 'timestamp' }),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt:  integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  activeIdx: index('api_provider_active_idx').on(table.isActive),
}));

export const apiProviderUsages = sqliteTable('ApiProviderUsage', {
  id:         text('id').primaryKey().$defaultFn(generateId),
  providerId: text('providerId').notNull().references(() => apiProviders.id, { onDelete: 'Cascade' }),
  operation:  text('operation').notNull(),
  tokensIn:   integer('tokensIn'),
  tokensOut:  integer('tokensOut'),
  cost:       real('cost'),
  success:    integer('success', { mode: 'boolean' }).notNull().default(true),
  errorMsg:   text('errorMsg'),
  durationMs: integer('durationMs'),
  createdAt:  integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  providerIdx: index('api_usage_provider_idx').on(table.providerId),
  createdAtIdx: index('api_usage_created_at_idx').on(table.createdAt),
}));

export const errorLogs = sqliteTable('ErrorLog', {
  id:           text('id').primaryKey().$defaultFn(generateId),
  source:       text('source').notNull(), // 'client' | 'server' | 'api' | 'cron'
  level:        text('level').notNull().default('ERROR'), // DEBUG | INFO | WARN | ERROR | FATAL
  message:      text('message').notNull(),
  stack:        text('stack'),
  url:          text('url'),
  method:       text('method'),
  statusCode:   integer('statusCode'),
  userId:       text('userId').references(() => users.id, { onDelete: 'SetNull' }),
  context:      text('context', { mode: 'json' }).$type<Record<string, any>>(),
  agentSeen:    integer('agentSeen', { mode: 'boolean' }).notNull().default(false),
  createdAt:    integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  sourceIdx: index('error_log_source_idx').on(table.source),
  levelIdx: index('error_log_level_idx').on(table.level),
  agentSeenIdx: index('error_log_agent_seen_idx').on(table.agentSeen),
  createdAtIdx: index('error_log_created_at_idx').on(table.createdAt),
}));

export const vercelLogs = sqliteTable('VercelLog', {
  id:           text('id').primaryKey().$defaultFn(generateId),
  requestId:    text('requestId'),
  requestPath:  text('requestPath'),
  requestMethod: text('requestMethod'),
  responseStatusCode: integer('responseStatusCode'),
  userAgent:    text('userAgent'),
  ipAddress:    text('ipAddress'),
  country:      text('country'),
  region:       text('region'),
  city:         text('city'),
  durationMs:   integer('durationMs'),
  createdAt:    integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
}, (table) => ({
  requestPathIdx: index('vercel_log_path_idx').on(table.requestPath),
  statusIdx: index('vercel_log_status_idx').on(table.responseStatusCode),
  createdAtIdx: index('vercel_log_created_at_idx').on(table.createdAt),
}));

// ============================================================================
// RELATIONS (Drizzle)
// ============================================================================
export const usersRelations = relations(users, ({ many, one }) => ({
  sessions: many(sessions),
  otpCodes: many(otpCodes),
  uploadedResources: many(resources, { relationName: 'UploadedBy' }),
  comments: many(comments),
  ratings: many(ratings),
  favorites: many(favorites),
  views: many(views),
  downloads: many(downloads),
  reports: many(reports),
  teacherFiles: many(teacherFiles),
  verifications: many(teacherVerificationFiles),
  notifications: many(notifications),
  followers: many(follows, { relationName: 'Follower' }),
  following: many(follows, { relationName: 'Following' }),
  conversations1: many(conversations, { relationName: 'User1' }),
  conversations2: many(conversations, { relationName: 'User2' }),
  messages: many(messages),
  searchLogs: many(searchLogs),
  errorLogs: many(errorLogs),
  approvedBy: one(users, { fields: [], references: [], relationName: 'Approver' }),
}));

export const otpCodesRelations = relations(otpCodes, ({ one }) => ({
  user: one(users, { fields: [otpCodes.userId], references: [users.id] }),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const levelsRelations = relations(levels, ({ many }) => ({
  classes: many(classes),
}));

export const classesRelations = relations(classes, ({ one, many }) => ({
  level: one(levels, { fields: [classes.levelId], references: [levels.id] }),
  resources: many(resources),
}));

export const sectionsRelations = relations(sections, ({ many }) => ({
  resources: many(resources),
}));

export const subjectsRelations = relations(subjects, ({ many }) => ({
  resources: many(resources),
}));

export const resourcesRelations = relations(resources, ({ one, many }) => ({
  class: one(classes, { fields: [resources.classId], references: [classes.id] }),
  section: one(sections, { fields: [resources.sectionId], references: [sections.id] }),
  subject: one(subjects, { fields: [resources.subjectId], references: [subjects.id] }),
  teacher: one(users, { fields: [resources.teacherId], references: [users.id], relationName: 'UploadedBy' }),
  content: one(resourceContents, { fields: [resources.id], references: [resourceContents.resourceId] }),
  metadata: one(resourceMetadata, { fields: [resources.id], references: [resourceMetadata.resourceId] }),
  summary: one(resourceSummaries, { fields: [resources.id], references: [resourceSummaries.resourceId] }),
  comments: many(comments, { relationName: 'ResourceComments' }),
  ratings: many(ratings, { relationName: 'ResourceRatings' }),
  favorites: many(favorites, { relationName: 'ResourceFavorites' }),
  views: many(views, { relationName: 'ResourceViews' }),
  downloads: many(downloads, { relationName: 'ResourceDownloads' }),
  shares: many(shares, { relationName: 'ResourceShares' }),
  reports: many(reports, { relationName: 'ResourceReports' }),
  teacherFiles: many(teacherFiles),
  searchLogs: many(searchLogs),
}));

export const resourceContentsRelations = relations(resourceContents, ({ one }) => ({
  resource: one(resources, { fields: [resourceContents.resourceId], references: [resources.id] }),
}));

export const resourceMetadataRelations = relations(resourceMetadata, ({ one }) => ({
  resource: one(resources, { fields: [resourceMetadata.resourceId], references: [resources.id] }),
}));

export const resourceSummariesRelations = relations(resourceSummaries, ({ one }) => ({
  resource: one(resources, { fields: [resourceSummaries.resourceId], references: [resources.id] }),
}));

export const commentsRelations = relations(comments, ({ one }) => ({
  resource: one(resources, { fields: [comments.resourceId], references: [resources.id], relationName: 'ResourceComments' }),
  user: one(users, { fields: [comments.userId], references: [users.id] }),
}));

export const ratingsRelations = relations(ratings, ({ one }) => ({
  resource: one(resources, { fields: [ratings.resourceId], references: [resources.id], relationName: 'ResourceRatings' }),
  user: one(users, { fields: [ratings.userId], references: [users.id] }),
}));

export const favoritesRelations = relations(favorites, ({ one }) => ({
  resource: one(resources, { fields: [favorites.resourceId], references: [resources.id], relationName: 'ResourceFavorites' }),
  user: one(users, { fields: [favorites.userId], references: [users.id] }),
}));

export const viewsRelations = relations(views, ({ one }) => ({
  resource: one(resources, { fields: [views.resourceId], references: [resources.id], relationName: 'ResourceViews' }),
  user: one(users, { fields: [views.userId], references: [users.id] }),
}));

export const downloadsRelations = relations(downloads, ({ one }) => ({
  resource: one(resources, { fields: [downloads.resourceId], references: [resources.id], relationName: 'ResourceDownloads' }),
  user: one(users, { fields: [downloads.userId], references: [users.id] }),
}));

export const sharesRelations = relations(shares, ({ one }) => ({
  resource: one(resources, { fields: [shares.resourceId], references: [resources.id], relationName: 'ResourceShares' }),
  user: one(users, { fields: [shares.userId], references: [users.id] }),
}));

export const reportsRelations = relations(reports, ({ one }) => ({
  resource: one(resources, { fields: [reports.resourceId], references: [resources.id], relationName: 'ResourceReports' }),
  user: one(users, { fields: [reports.userId], references: [users.id] }),
}));

export const teacherFilesRelations = relations(teacherFiles, ({ one }) => ({
  teacher: one(users, { fields: [teacherFiles.teacherId], references: [users.id] }),
  resource: one(resources, { fields: [teacherFiles.resourceId], references: [resources.id] }),
}));

export const teacherVerificationFilesRelations = relations(teacherVerificationFiles, ({ one }) => ({
  user: one(users, { fields: [teacherVerificationFiles.userId], references: [users.id] }),
}));

export const notificationsRelations = relations(notifications, ({ one }) => ({
  user: one(users, { fields: [notifications.userId], references: [users.id] }),
}));

export const followsRelations = relations(follows, ({ one }) => ({
  follower: one(users, { fields: [follows.followerId], references: [users.id], relationName: 'Follower' }),
  following: one(users, { fields: [follows.followingId], references: [users.id], relationName: 'Following' }),
}));

export const conversationsRelations = relations(conversations, ({ one, many }) => ({
  user1: one(users, { fields: [conversations.user1Id], references: [users.id], relationName: 'User1' }),
  user2: one(users, { fields: [conversations.user2Id], references: [users.id], relationName: 'User2' }),
  messages: many(messages),
}));

export const messagesRelations = relations(messages, ({ one }) => ({
  conversation: one(conversations, { fields: [messages.conversationId], references: [conversations.id] }),
  sender: one(users, { fields: [messages.senderId], references: [users.id] }),
}));

export const searchLogsRelations = relations(searchLogs, ({ one }) => ({
  user: one(users, { fields: [searchLogs.userId], references: [users.id] }),
  clickedResource: one(resources, { fields: [searchLogs.clickedResourceId], references: [resources.id] }),
}));

export const apiProvidersRelations = relations(apiProviders, ({ many }) => ({
  usages: many(apiProviderUsages),
}));

export const apiProviderUsagesRelations = relations(apiProviderUsages, ({ one }) => ({
  provider: one(apiProviders, { fields: [apiProviderUsages.providerId], references: [apiProviders.id] }),
}));

export const errorLogsRelations = relations(errorLogs, ({ one }) => ({
  user: one(users, { fields: [errorLogs.userId], references: [users.id] }),
}));

// ============================================================================
// EXPORT EVERYTHING
// ============================================================================
export const schema = {
  users, otpCodes, sessions,
  levels, classes, sections, subjects,
  resources, resourceContents, resourceMetadata, resourceSummaries,
  teacherVerificationFiles, teacherFiles,
  comments, ratings, favorites, views, downloads, shares, reports,
  notifications, newsletters, teacherInvitations, settings, follows,
  conversations, messages, contactMessages,
  searchSynonyms, searchLogs,
  apiProviders, apiProviderUsages,
  errorLogs, vercelLogs,
};

export type Schema = typeof schema;
