// Build-time script: reads /content/referentiel-source.html and generates
// /src/data/referentiel-source.ts with the content embedded
// This replaces fs.readFileSync which doesn't work on CF Workers
import fs from 'fs';
import path from 'path';

const html = fs.readFileSync(
  path.join(process.cwd(), 'content/referentiel-source.html'),
  'utf-8'
);

const output = `// Auto-generated by scripts/embed-referentiel.ts
// Embedded content of /content/referentiel-source.html for CF Workers
// (fs.readFileSync doesn't work at runtime on CF Workers)
export const REFERENTIEL_SOURCE = ${JSON.stringify(html)};
`;

fs.writeFileSync(
  path.join(process.cwd(), 'src/data/referentiel-source.ts'),
  output
);

console.log(`Embedded ${html.length} bytes of referentiel HTML`);
