/**
 * Build-time script: embeds the Concours 9ème manifest into the bundle.
 * This avoids fs.readFileSync at runtime on CF Workers.
 * 
 * Output: src/data/concours-9eme-manifest.ts
 */
import fs from 'node:fs';
import path from 'node:path';

const input = path.join(process.cwd(), 'public', 'data', 'concours-9eme-manifest.json');
const output = path.join(process.cwd(), 'src', 'data', 'concours-9eme-manifest.ts');

const manifest = fs.readFileSync(input, 'utf-8');
const parsed = JSON.parse(manifest);

const ts = `// Auto-generated by scripts/embed-concours-manifest.ts
// Embedded data from /public/data/concours-9eme-manifest.json
// (fs.readFileSync doesn't work at runtime on CF Workers)
export const CONCOURS_9EME_MANIFEST = ${JSON.stringify(parsed, null, 2)};
`;

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, ts, 'utf-8');
console.log(`✅ Wrote ${output} (${(ts.length / 1024).toFixed(1)}KB)`);
