/**
 * Build-time script: embeds the BAC manifest into the bundle.
 * This avoids fs.readFileSync at runtime on CF Workers.
 * 
 * The full manifest is 1.5MB, so we only embed the essential fields:
 * key, url, size, year, section, session, type, subject
 * 
 * Output: src/data/bac-manifest.ts
 */
import fs from 'node:fs';
import path from 'node:path';

const input = path.join(process.cwd(), 'public', 'data', 'bac-manifest.json');
const output = path.join(process.cwd(), 'src', 'data', 'bac-manifest.ts');

const raw = fs.readFileSync(input, 'utf-8');
const parsed = JSON.parse(raw);

// Slim down the uploaded entries to only essential fields
const slim = {
  ...parsed,
  uploaded: (parsed.uploaded || []).map((u: any) => ({
    key: u.key,
    url: u.url,
    size: u.size,
    year: u.year,
    section: u.section,
    sectionRaw: u.sectionRaw,
    session: u.session,
    type: u.type,
    subject: u.subject,
  })),
};

const ts = `// Auto-generated by scripts/embed-bac-manifest.ts
// Embedded data from /public/data/bac-manifest.json (slim version)
// (fs.readFileSync doesn't work at runtime on CF Workers)
export const BAC_MANIFEST = ${JSON.stringify(slim, null, 2)};
`;

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, ts, 'utf-8');
console.log(`✅ Wrote ${output} (${(ts.length / 1024 / 1024).toFixed(2)}MB)`);
